# Generated by Django 3.2 on 2022-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('ammount_Balance', models.CharField(max_length=300)),
                ('place_id', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
