# Generated by Django 3.2 on 2022-04-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_auto_20220421_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
