# Generated by Django 3.2 on 2022-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_alter_parties_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='contact',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='email_id',
            field=models.CharField(blank=True, default='none', max_length=300, null=True),
        ),
    ]
