# Generated by Django 3.2 on 2022-10-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_partyloans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='contact',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
