# Generated by Django 3.2 on 2022-09-18 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(blank=True, max_length=300)),
                ('user2', models.CharField(blank=True, max_length=300)),
                ('date', models.CharField(default=datetime.date(2022, 9, 18), max_length=300)),
            ],
        ),
    ]
