# Generated by Django 3.2 on 2022-09-20 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accessusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='dateofcreation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userfield',
            name='fullname',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='accessusers',
            name='date',
            field=models.CharField(default=datetime.date(2022, 9, 20), max_length=300),
        ),
    ]
