# Generated by Django 3.2 on 2022-10-10 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userfield_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessusers',
            name='date',
            field=models.CharField(default=datetime.date(2022, 10, 10), max_length=300),
        ),
    ]
