# Generated by Django 3.2 on 2022-03-29 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closedcostumers', '0002_remove_costumers_closeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumers',
            name='loanclose',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
